apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: gke-application
build:
  artifacts:
  - image: pop-stats
    context: app
    docker:
      dockerfile: Dockerfile
deploy:
  # The deploy stanza for the default (test) environment
  kustomize:
    paths:
      - k8s/overlays/dev
portForward:
- resourceType: deployment
  resourceName: pop-stats
  port: 8080
  localPort: 8080
profiles:
  - name: staging
    # The deploy stanza for the staging environment
    deploy:
      kustomize:
        paths:
          - k8s/overlays/staging
  - name: prod
    # The deploy stanza for the prod environment
    deploy:
      kustomize:
        paths:
          - k8s/overlays/prod
